- name: Playbook do side kid
  hosts:  all
  tasks:
  
  - name: Stop NGINX
    systemd: 
      name: nginx
      state: stopped

  - name: Desinsitalar o NGINX
    package:
      name: nginx*
      state: absent

  - name: INSTALANDO o Apache2 "Ubuntu"
    package:
      name: ['apache2','libapache2-mod-php7.0','php7.0']
      state: present
    when: ansible_distribution == "Ubuntu"
  
  - name: Habilita modulo PHP UBUNTU
    apache2_module:
      name: php7.0
      state: present
    notify: apache2    
    when: ansible_distribution == "Ubuntu"

  - name: INSTALANDO PHP HTTPD - "CentOS"
    package:
      name: ['httpd','php']
      state: present
    notify: httpd
    when: ansible_distribution == "CentOS"

  - name: Criando index.php
    copy:
      src: index.php
      dest: /var/www/html/

  handlers:
  - name: httpd
    systemd:
      name: httpd
      state: restarted
  - name: apache2
    systemd:
      name: apache2
      state: restarded

  






























     
